//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListerHaigh.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentAttendee
    {
        public int DetailId { get; set; }
        public Nullable<int> AppointmentId { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
