//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListerHaigh.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppointmentId { get; set; }
        public Nullable<int> EventType { get; set; }
        public string Subject { get; set; }
        public Nullable<int> AppointmentType { get; set; }
        public Nullable<int> AppointmentDuration { get; set; }
        public Nullable<bool> IsPrivate { get; set; }
        public Nullable<bool> IsRecordLocked { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public string Details { get; set; }
        public Nullable<int> PropertyId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> EventStartDate { get; set; }
        public Nullable<System.DateTime> EventEndDate { get; set; }
        public Nullable<System.TimeSpan> EventStartTime { get; set; }
        public Nullable<System.TimeSpan> EventEndTime { get; set; }
        public Nullable<bool> IsReminderPopup { get; set; }
        public string BookingNotes { get; set; }
        public Nullable<int> Recurrence { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
