//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListerHaigh.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int AttachmentId { get; set; }
        public Nullable<int> PropertyId { get; set; }
        public Nullable<int> JobId { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public string FileName { get; set; }
        public string MimeType { get; set; }
        public string AttachmentDescription { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool IsImage { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual Property Property { get; set; }
    }
}
