//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListerHaigh.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public System.DateTime EventDate { get; set; }
        public string EventType { get; set; }
        public string TableName { get; set; }
        public int RecordId { get; set; }
        public string RecordType { get; set; }
        public string ColumnName { get; set; }
        public string OriginalValue { get; set; }
        public string NewValue { get; set; }
        public Nullable<int> SiteId { get; set; }
    }
}
