//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListerHaigh.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComparableRecord
    {
        public ComparableRecord()
        {
            this.PropertyHistories = new HashSet<PropertyHistory>();
        }
    
        public int ComparableRecordId { get; set; }
        public Nullable<int> OfficeId { get; set; }
        public string FileK { get; set; }
        public string FileH { get; set; }
        public string SalesPartiesComp { get; set; }
        public Nullable<int> PropertyId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> EventId { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<int> TypeOneId { get; set; }
        public Nullable<int> TypeTwoId { get; set; }
        public string Bedrooms { get; set; }
        public string Baths { get; set; }
        public string Receptions { get; set; }
        public string Garage { get; set; }
        public string Garden { get; set; }
        public string Land { get; set; }
        public Nullable<decimal> GuidePrice { get; set; }
        public string SellingAgent { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsRecorded { get; set; }
        public bool Deleted { get; set; }
        public string FirmReference { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Department Department { get; set; }
        public virtual Event Event { get; set; }
        public virtual Property Property { get; set; }
        public virtual TypeOne TypeOne { get; set; }
        public virtual TypeTwo TypeTwo { get; set; }
        public virtual ICollection<PropertyHistory> PropertyHistories { get; set; }
    }
}
