//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListerHaigh.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.ComparableRecords = new HashSet<ComparableRecord>();
            this.CustomerSubscriptions = new HashSet<CustomerSubscription>();
            this.JobClients = new HashSet<JobClient>();
            this.Jobs = new HashSet<Job>();
        }
    
        public int CustomerID { get; set; }
        public string Initial { get; set; }
        public string ContactName { get; set; }
        public string SurName { get; set; }
        public string Status { get; set; }
        public string SBINumber { get; set; }
        public string HoldingNumber { get; set; }
        public string TelNumber { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string EmailAddress { get; set; }
        public string Address { get; set; }
        public string Street { get; set; }
        public string Village { get; set; }
        public Nullable<int> Town { get; set; }
        public Nullable<int> County { get; set; }
        public string PostCode { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<bool> IsIDRequired { get; set; }
        public Nullable<bool> IsMoneyLaundering { get; set; }
        public bool Enabled { get; set; }
        public bool Deleted { get; set; }
        public bool SubscribeNewsletter { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual ICollection<ComparableRecord> ComparableRecords { get; set; }
        public virtual County County1 { get; set; }
        public virtual Town Town1 { get; set; }
        public virtual ICollection<CustomerSubscription> CustomerSubscriptions { get; set; }
        public virtual ICollection<JobClient> JobClients { get; set; }
        public virtual ICollection<Job> Jobs { get; set; }
    }
}
