//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListerHaigh.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardSection
    {
        public DashboardSection()
        {
            this.ModuleItems = new HashSet<ModuleItem>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool Enabled { get; set; }
        public string Url { get; set; }
        public string IconClass { get; set; }
        public byte SortOrder { get; set; }
        public bool HasModules { get; set; }
        public Nullable<bool> isVisible { get; set; }
    
        public virtual ICollection<ModuleItem> ModuleItems { get; set; }
    }
}
