//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListerHaigh.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.Attachments = new HashSet<Attachment>();
            this.JobAllocations = new HashSet<JobAllocation>();
            this.JobClients = new HashSet<JobClient>();
            this.JobEvents = new HashSet<JobEvent>();
            this.JobExpenses = new HashSet<JobExpens>();
            this.PropertyHistories = new HashSet<PropertyHistory>();
            this.WorkDetails = new HashSet<WorkDetail>();
        }
    
        public int JobId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> PropertyId { get; set; }
        public Nullable<int> OfficeId { get; set; }
        public string JobYear { get; set; }
        public string JobNumber { get; set; }
        public Nullable<int> JobCode { get; set; }
        public Nullable<int> SubCode { get; set; }
        public string Description { get; set; }
        public string SiteReference { get; set; }
        public Nullable<System.DateTime> InstructedDate { get; set; }
        public Nullable<System.TimeSpan> InstructedTime { get; set; }
        public string InstructionSource { get; set; }
        public Nullable<int> TypeOneId { get; set; }
        public Nullable<int> TypeTwoId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> EventId { get; set; }
        public Nullable<bool> AgNewsletter { get; set; }
        public Nullable<bool> TimeRecord { get; set; }
        public string ValnBkReference { get; set; }
        public Nullable<decimal> BudgetFee { get; set; }
        public Nullable<bool> CR { get; set; }
        public Nullable<System.DateTime> FinishDateTarget { get; set; }
        public Nullable<System.DateTime> ValuationSent { get; set; }
        public Nullable<int> JobStatus { get; set; }
        public string InvNumber { get; set; }
        public Nullable<System.DateTime> FClosed { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual ICollection<Attachment> Attachments { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Department Department { get; set; }
        public virtual Event Event { get; set; }
        public virtual ICollection<JobAllocation> JobAllocations { get; set; }
        public virtual ICollection<JobClient> JobClients { get; set; }
        public virtual JobCode JobCode1 { get; set; }
        public virtual ICollection<JobEvent> JobEvents { get; set; }
        public virtual ICollection<JobExpens> JobExpenses { get; set; }
        public virtual JobSubCode JobSubCode { get; set; }
        public virtual Office Office { get; set; }
        public virtual Property Property { get; set; }
        public virtual TypeOne TypeOne { get; set; }
        public virtual TypeTwo TypeTwo { get; set; }
        public virtual ICollection<PropertyHistory> PropertyHistories { get; set; }
        public virtual ICollection<WorkDetail> WorkDetails { get; set; }
    }
}
