//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListerHaigh.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobCode
    {
        public JobCode()
        {
            this.Jobs = new HashSet<Job>();
            this.JobSubCodes = new HashSet<JobSubCode>();
        }
    
        public int CodeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool Enabled { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<Job> Jobs { get; set; }
        public virtual ICollection<JobSubCode> JobSubCodes { get; set; }
    }
}
