//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListerHaigh.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobExpens
    {
        public int ExpenseId { get; set; }
        public Nullable<int> JobId { get; set; }
        public Nullable<System.DateTime> ExpenseDate { get; set; }
        public Nullable<decimal> Postage { get; set; }
        public string Details { get; set; }
        public Nullable<decimal> PhotoCopying { get; set; }
        public Nullable<decimal> Telephone { get; set; }
        public Nullable<decimal> PlansDisbursements { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
