//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListerHaigh.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobEvent
    {
        public int JobEventId { get; set; }
        public Nullable<int> JobId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> EventId { get; set; }
        public Nullable<int> TypeOneId { get; set; }
        public Nullable<int> TypeTwoId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Size { get; set; }
        public Nullable<int> SizeUnit { get; set; }
        public string Tenure { get; set; }
        public string Occupation { get; set; }
        public Nullable<decimal> CapitalValue { get; set; }
        public Nullable<decimal> Rental { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<decimal> SqMeterValue { get; set; }
        public Nullable<decimal> MeterValue { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Event Event { get; set; }
        public virtual Job Job { get; set; }
        public virtual TypeOne TypeOne { get; set; }
        public virtual TypeTwo TypeTwo { get; set; }
    }
}
