//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListerHaigh.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSubCode
    {
        public JobSubCode()
        {
            this.Jobs = new HashSet<Job>();
        }
    
        public int SubCodeId { get; set; }
        public Nullable<int> JobCodeId { get; set; }
        public string Name { get; set; }
        public string SageCode { get; set; }
        public bool Enabled { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string Description { get; set; }
        public string Prefix { get; set; }
        public bool Deleted { get; set; }
    
        public virtual JobCode JobCode { get; set; }
        public virtual ICollection<Job> Jobs { get; set; }
    }
}
