//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListerHaigh.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ListerHaighEntites : DbContext
    {
        public ListerHaighEntites()
            : base("name=ListerHaighEntites")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppointmentAttendee> AppointmentAttendees { get; set; }
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<Attachment> Attachments { get; set; }
        public virtual DbSet<AuditLog> AuditLogs { get; set; }
        public virtual DbSet<ComparableRecord> ComparableRecords { get; set; }
        public virtual DbSet<County> Counties { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerSubscription> CustomerSubscriptions { get; set; }
        public virtual DbSet<DashboardSection> DashboardSections { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<JobAllocation> JobAllocations { get; set; }
        public virtual DbSet<JobClient> JobClients { get; set; }
        public virtual DbSet<JobCode> JobCodes { get; set; }
        public virtual DbSet<JobEvent> JobEvents { get; set; }
        public virtual DbSet<JobExpens> JobExpenses { get; set; }
        public virtual DbSet<JobNumber> JobNumbers { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<JobSubCode> JobSubCodes { get; set; }
        public virtual DbSet<ListItem> ListItems { get; set; }
        public virtual DbSet<ListType> ListTypes { get; set; }
        public virtual DbSet<ModuleItem> ModuleItems { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<Office> Offices { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Preference> Preferences { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
        public virtual DbSet<PropertyHistory> PropertyHistories { get; set; }
        public virtual DbSet<PropertyReferenceNumber> PropertyReferenceNumbers { get; set; }
        public virtual DbSet<SecurityAction> SecurityActions { get; set; }
        public virtual DbSet<Town> Towns { get; set; }
        public virtual DbSet<TypeOne> TypeOnes { get; set; }
        public virtual DbSet<TypeTwo> TypeTwoes { get; set; }
        public virtual DbSet<UrlRedirect> UrlRedirects { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ValidationType> ValidationTypes { get; set; }
        public virtual DbSet<webpages_Membership> webpages_Membership { get; set; }
        public virtual DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }
        public virtual DbSet<WorkDetail> WorkDetails { get; set; }
    }
}
