//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListerHaigh.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office
    {
        public Office()
        {
            this.Jobs = new HashSet<Job>();
            this.Users = new HashSet<User>();
        }
    
        public int OfficeId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public bool Enabled { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModfiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool Deleted { get; set; }
    
        public virtual ICollection<Job> Jobs { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
