//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListerHaigh.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public int Id { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public Nullable<int> ModuleItemId { get; set; }
        public Nullable<int> SecurityActionId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ContentId { get; set; }
        public string ContentType { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> SiteId { get; set; }
    
        public virtual ModuleItem ModuleItem { get; set; }
        public virtual Module Module { get; set; }
        public virtual SecurityAction SecurityAction { get; set; }
        public virtual webpages_Roles webpages_Roles { get; set; }
    }
}
