//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListerHaigh.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public Property()
        {
            this.Attachments = new HashSet<Attachment>();
            this.ComparableRecords = new HashSet<ComparableRecord>();
            this.Jobs = new HashSet<Job>();
            this.PropertyHistories = new HashSet<PropertyHistory>();
            this.PropertyHistories1 = new HashSet<PropertyHistory>();
        }
    
        public int PropertyId { get; set; }
        public string Name { get; set; }
        public string Street { get; set; }
        public string Address { get; set; }
        public string Village { get; set; }
        public Nullable<int> Town { get; set; }
        public Nullable<int> County { get; set; }
        public string PostCode { get; set; }
        public string GPS { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> EventId { get; set; }
        public string Type { get; set; }
        public string Type2 { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string SellingAgent { get; set; }
        public string Remarks { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual ICollection<Attachment> Attachments { get; set; }
        public virtual ICollection<ComparableRecord> ComparableRecords { get; set; }
        public virtual County County1 { get; set; }
        public virtual Event Event { get; set; }
        public virtual ICollection<Job> Jobs { get; set; }
        public virtual Town Town1 { get; set; }
        public virtual ICollection<PropertyHistory> PropertyHistories { get; set; }
        public virtual ICollection<PropertyHistory> PropertyHistories1 { get; set; }
    }
}
