//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListerHaigh.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkDetail
    {
        public int WorkDetailId { get; set; }
        public Nullable<int> PropertyId { get; set; }
        public Nullable<int> JobId { get; set; }
        public Nullable<System.DateTime> WorkDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> Hrs { get; set; }
        public Nullable<int> Mins { get; set; }
        public string TravelTime { get; set; }
        public string CarMiles { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.TimeSpan> FromTime { get; set; }
        public Nullable<System.TimeSpan> ToTime { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
